name: pdfocr
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  dart_pdf_reader: ^2.1.0
  args: ^2.7.0
  dcli: ^7.0.3
    #git:
      #url: https://github.com/onepub-dev/dcli.git
      #path: dcli
      #ref: 1ccfc5c

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
